export default {
  GAME_STATE: 'GAME_STATE',
  SET_DEALER: 'SET_DEALER',
  SET_GAME_STATE: 'SET_GAME_STATE',
  SET_CENTER_DEAL: 'SET_CENTER_DEAL',
  SET_PLAYER_COUNT: 'SET_PLAYER_COUNT',
  UPDATE_ROUND_QUEUE: 'UPDATE_ROUND_QUEUE',
  UPDATE_DEALER_QUEUE: 'UPDATE_DEALER_QUEUE',
  SET_ROUND: 'SET_ROUND',
  SET_MATCH_COUNT: 'SET_MATCH_COUNT',
}